Orders with api connection
Anders164a/surstroem pull request #4
Opened 2022-03-01 10:23 UTC by DavidSKoppel

Build CRUD for Orders and OrderProduct, and established connection with another api

2022-03-01 10:29 UTC, Minhly approved these changes

2022-03-08 11:50 UTC, Anders164a requested changes
See comments

2022-03-08 11:50 UTC, Anders164a commented on API/Controllers/DogDto.cs
> +    public class DogDto
Remove

2022-03-08 11:56 UTC, DavidSKoppel commented on API/Controllers/DogDto.cs
> +    public class DogDto
Done

2022-03-08 11:58 UTC, Anders164a approved these changes

2022-03-08 12:00 UTC, merged